# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -y update
    apt-get -y install rubygems
    echo 'gem: --no-ri --no-rdoc' > ~/.gemrc
    gem install librarian-puppet
    apt-get install -y puppet
    (cd /vagrant && librarian-puppet install)
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
    #puppet.options = "--verbose"
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    echo " "
    echo "----"
    echo " "
    echo "Testing. You should see HTML below."
    wget -qO- localhost
    echo " "
    echo "----"
    echo " "
    echo "You can also test at http://localhost:8080 from your host system."
  SHELL
end
