# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -y update
    apt-get -y install rubygems
    echo 'gem: --no-ri --no-rdoc' > ~/.gemrc
    apt-get install -y puppet
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
    #puppet.options = "--verbose"
  end
end
